# Generated by Django 5.2.1 on 2025-05-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_availability_item_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image2',
        ),
    ]
