# Generated by Django 5.2.1 on 2025-05-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_item_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='media/item_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/item_videos/'),
        ),
    ]
