# Generated by Django 5.2.1 on 2025-11-21 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_category_level_category_parent_category'),
        ('item', '0006_alter_item_image1_alter_item_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_items', to='category.category'),
        ),
    ]
