# Generated by Django 5.2.1 on 2025-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_item_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
