# Generated by Django 5.2.1 on 2026-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_icon_image'),
        ('item', '0009_item_tags'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['restaurant'], name='item_item_restaur_26d236_idx'),
        ),
    ]
