import { useState } from "react";
import { Link, useNavigate } from "react-router";
import { Loader2, Store, User, MapPin, CheckCircle, ChevronRight, ArrowLeft, Upload, Phone as PhoneIcon } from "lucide-react";
import axiosInstance from "@/lib/axios";
import toast from "react-hot-toast";

const ScreenAdminRegister = () => {
    const navigate = useNavigate();
    const [step, setStep] = useState<'gate' | 'details' | 'restaurant'>('gate');
    const [isLoading, setIsLoading] = useState(false);

    // Gate State
    const [accessCode, setAccessCode] = useState(["", "", "", ""]);

    // Registration State
    const [formData, setFormData] = useState({
        email: "",
        password: "",
        confirmPassword: "",
        resturent_name: "",
        location: "",
        phone_number: "",
        package: "Basic",
    });

    // Access Code Logic
    const handleCodeChange = (index: number, value: string) => {
        if (value.length > 1) return;
        const newCode = [...accessCode];
        newCode[index] = value;
        setAccessCode(newCode);

        // Auto-focus next
        if (value && index < 3) {
            const nextInput = document.getElementById(`code-${index + 1}`);
            nextInput?.focus();
        }
    };

    const verifyCode = () => {
        const code = accessCode.join("");
        if (code === "2468") {
            toast.success("Access Granted");
            setStep('details');
        } else {
            toast.error("Invalid Access Code");
            setAccessCode(["", "", "", ""]);
            document.getElementById("code-0")?.focus();
        }
    };

    const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => {
        setFormData({ ...formData, [e.target.name]: e.target.value });
    };

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (formData.password !== formData.confirmPassword) {
            toast.error("Passwords do not match");
            return;
        }

        setIsLoading(true);

        try {
            // Note: username is auto-generated by backend if not provided.
            // We only send the fields we have.
            const payload = {
                email: formData.email,
                password: formData.password,
                resturent_name: formData.resturent_name,
                location: formData.location,
                phone_number: formData.phone_number,
                package: formData.package
            };

            await axiosInstance.post(`/owners/registered-restaurants/`, payload);

            toast.success("Restaurant registered successfully!");
            navigate("/adminlogin");

        } catch (error: any) {
            console.error(error);
            const msg = error.response?.data?.error ||
                error.response?.data?.email?.[0] ||
                error.response?.data?.phone_number?.[0] ||
                "Registration failed.";
            toast.error(msg);
        } finally {
            setIsLoading(false);
        }
    };

    // --- RENDER STEPS ---

    const renderGate = () => (
        <div className="max-w-md w-full mx-auto text-center animate-fadeIn">
            <div className="bg-blue-50 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-6">
                <Store className="w-10 h-10 text-[#0055FE]" />
            </div>
            <h1 className="text-3xl font-bold text-slate-900 mb-3">Partner Access</h1>
            <p className="text-slate-500 mb-8">Enter the 4-digit access code provided by CleverBiz.</p>

            <div className="flex gap-4 justify-center mb-8">
                {accessCode.map((digit, idx) => (
                    <input
                        key={idx}
                        id={`code-${idx}`}
                        type="text"
                        maxLength={1}
                        value={digit}
                        onChange={(e) => handleCodeChange(idx, e.target.value)}
                        className="w-14 h-16 text-center text-2xl font-bold border-2 border-slate-200 rounded-xl focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none transition-all"
                    />
                ))}
            </div>

            <button
                onClick={verifyCode}
                className="w-full h-12 bg-[#0055FE] hover:bg-[#0047D1] text-white font-semibold rounded-lg shadow-lg shadow-blue-500/20 transition-all"
            >
                Verify Access
            </button>

            <button onClick={() => navigate('/adminlogin')} className="mt-6 text-slate-400 hover:text-slate-600 text-sm">
                Back to Login
            </button>
        </div>
    );

    const renderDetails = () => (
        <div className="max-w-[480px] w-full mx-auto animate-fadeIn">
            <button onClick={() => setStep('gate')} className="mb-6 text-slate-500 hover:text-[#0055FE] flex items-center gap-2 text-sm transition-colors">
                <ArrowLeft size={16} /> Back
            </button>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">Create Account</h1>
            <p className="text-slate-500 mb-8">Step 1 of 2: Owner Credentials</p>

            <div className="space-y-4">
                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Email Address</label>
                    <div className="relative">
                        <User className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                        <input
                            type="email"
                            name="email"
                            required
                            value={formData.email}
                            onChange={handleInputChange}
                            className="w-full pl-10 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none"
                            placeholder="owner@restaurant.com"
                        />
                    </div>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Password</label>
                    <input
                        type="password"
                        name="password"
                        required
                        value={formData.password}
                        onChange={handleInputChange}
                        className="w-full px-4 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none"
                        placeholder="Create a strong password"
                    />
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Confirm Password</label>
                    <input
                        type="password"
                        name="confirmPassword"
                        required
                        value={formData.confirmPassword}
                        onChange={handleInputChange}
                        className="w-full px-4 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none"
                        placeholder="Repeat password"
                    />
                </div>

                <button
                    onClick={() => {
                        if (formData.email && formData.password && formData.password === formData.confirmPassword) {
                            setStep('restaurant');
                        } else {
                            toast.error("Please fill all fields correctly");
                        }
                    }}
                    className="w-full h-12 mt-4 bg-[#0055FE] hover:bg-[#0047D1] text-white font-semibold rounded-lg shadow-lg shadow-blue-500/20 flex items-center justify-center gap-2 transition-all"
                >
                    Next Step <ChevronRight size={18} />
                </button>
            </div>
        </div>
    );

    const renderRestaurant = () => (
        <form onSubmit={handleSubmit} className="max-w-[480px] w-full mx-auto animate-fadeIn">
            <button type="button" onClick={() => setStep('details')} className="mb-6 text-slate-500 hover:text-[#0055FE] flex items-center gap-2 text-sm transition-colors">
                <ArrowLeft size={16} /> Back
            </button>
            <h1 className="text-3xl font-bold text-slate-900 mb-2">Restaurant Info</h1>
            <p className="text-slate-500 mb-8">Step 2 of 2: Business Details</p>

            <div className="space-y-4">
                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Restaurant Name</label>
                    <div className="relative">
                        <Store className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                        <input
                            type="text"
                            name="resturent_name"
                            required
                            value={formData.resturent_name}
                            onChange={handleInputChange}
                            className="w-full pl-10 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none"
                            placeholder="e.g. Bella Italia"
                        />
                    </div>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Location</label>
                    <div className="relative">
                        <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                        <input
                            type="text"
                            name="location"
                            required
                            value={formData.location}
                            onChange={handleInputChange}
                            className="w-full pl-10 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none"
                            placeholder="City, Area"
                        />
                    </div>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Phone Number</label>
                    <div className="relative">
                        <PhoneIcon className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                        <input
                            type="tel"
                            name="phone_number"
                            value={formData.phone_number}
                            onChange={handleInputChange}
                            className="w-full pl-10 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none"
                            placeholder="+971 50 123 4567"
                        />
                    </div>
                </div>

                <div className="space-y-2">
                    <label className="text-sm font-medium text-slate-700">Package Plan</label>
                    <select
                        name="package"
                        value={formData.package}
                        onChange={handleInputChange}
                        className="w-full px-4 h-11 border border-slate-200 rounded-lg focus:border-[#0055FE] focus:ring-4 focus:ring-[#0055FE]/10 outline-none bg-white"
                    >
                        <option value="Basic">Basic Plan</option>
                        <option value="Pro">Pro Plan</option>
                        <option value="Enterprise">Enterprise Plan</option>
                    </select>
                </div>

                <button
                    type="submit"
                    disabled={isLoading}
                    className="w-full h-12 mt-6 bg-[#0055FE] hover:bg-[#0047D1] text-white font-semibold rounded-lg shadow-lg shadow-blue-500/20 disabled:opacity-70 flex items-center justify-center gap-2 transition-all"
                >
                    {isLoading ? <Loader2 className="animate-spin" /> : <CheckCircle />}
                    {isLoading ? "creating Account..." : "Complete Registration"}
                </button>
            </div>
        </form>
    );

    return (
        <div className="flex min-h-screen bg-white font-inter">
            {/* Left Panel */}
            <div className="w-full lg:w-1/2 flex flex-col justify-center px-8 lg:px-24 py-12 relative">
                {step === 'gate' && renderGate()}
                {step === 'details' && renderDetails()}
                {step === 'restaurant' && renderRestaurant()}
            </div>

            {/* Right Panel - Consistent with Login */}
            <div className="hidden lg:flex w-1/2 relative bg-slate-900 overflow-hidden">
                <div className="absolute inset-0 bg-[url('/src/assets/hero-image-1.webp')] bg-cover bg-center opacity-60 mix-blend-overlay"></div>
                <div className="absolute inset-0 bg-gradient-to-t from-slate-900 via-slate-900/40 to-transparent"></div>
                <div className="relative z-10 w-full h-full flex flex-col justify-end p-12 lg:p-20">
                    <h2 className="text-4xl font-bold text-white mb-4 leading-tight">
                        Grow your business <br /> with CleverBiz AI.
                    </h2>
                    <p className="text-slate-300 text-lg max-w-md">
                        Join thousands of restaurants automating their operations and increasing revenue.
                    </p>
                </div>
            </div>
        </div>
    );
};

export default ScreenAdminRegister;
