# Generated by Django 5.2.1 on 2026-05-12 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0012_itemassociation'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('email', models.TextField(blank=True, null=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('lifetime_points', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_customers', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRestaurantLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.TextField(blank=True, null=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_links', to='customer.customer')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'customer_restaurant_links',
            },
        ),
        migrations.CreateModel(
            name='GameScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('player_name', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('game_type', models.TextField(default='snake')),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_scores', to='customer.customer')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_scores', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'game_scores',
                'ordering': ['-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField()),
                ('type', models.CharField(choices=[('earn_order', 'Earn Order'), ('earn_game', 'Earn Game'), ('redeem', 'Redeem'), ('bonus', 'Bonus'), ('expire', 'Expire')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='customer.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='order.order')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'loyalty_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['restaurant', 'created_at'], name='customers_restaur_a518cc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['tier'], name='customers_tier_094047_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrestaurantlink',
            index=models.Index(fields=['restaurant', 'last_visit'], name='customer_re_restaur_d0e0f4_idx'),
        ),
        migrations.AddIndex(
            model_name='customerrestaurantlink',
            index=models.Index(fields=['customer', 'last_visit'], name='customer_re_custome_decc43_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerrestaurantlink',
            unique_together={('customer', 'restaurant')},
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['game_type', 'score'], name='game_scores_game_ty_d09f12_idx'),
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['phone'], name='game_scores_phone_39583a_idx'),
        ),
        migrations.AddIndex(
            model_name='gamescore',
            index=models.Index(fields=['restaurant', 'created_at'], name='game_scores_restaur_e8632d_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['customer', 'created_at'], name='loyalty_tra_custome_dab941_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltytransaction',
            index=models.Index(fields=['restaurant', 'created_at'], name='loyalty_tra_restaur_d28a5e_idx'),
        ),
    ]
