# Generated by Django 5.2.1 on 2026-05-16 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(default='Guest')),
                ('phone', models.TextField(db_index=True)),
                ('source', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('walk-in', 'Walk-in'), ('reservation', 'Reservation'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('total_reservation_attempts', models.PositiveIntegerField(default=0)),
                ('total_confirmed_reservations', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'leads',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['restaurant', 'status'], name='leads_restaur_c499ce_idx'), models.Index(fields=['phone'], name='leads_phone_13acb4_idx'), models.Index(fields=['last_seen'], name='leads_last_se_50b48d_idx')],
                'unique_together': {('restaurant', 'phone')},
            },
        ),
    ]
