# Generated by Django 5.2.1 on 2025-07-12 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0008_remove_restaurant_starting_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_number', models.CharField(max_length=20, unique=True)),
                ('twilio_account_sid', models.CharField(max_length=500)),
                ('twilio_auth_token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistance', to='restaurant.restaurant')),
            ],
        ),
    ]
