# Generated by Django 5.2.1 on 2025-07-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='assistant_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistance',
            name='vapi_phone_number_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
