# Generated by Django 5.2.1 on 2025-08-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0002_assistance_assistant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='twilio_api_secret',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
