# Generated by Django 5.2.1 on 2025-08-07 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0003_assistance_twilio_api_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistance',
            name='twilio_api_secret',
        ),
    ]
