# Generated by Django 5.2.1 on 2025-08-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vapi', '0004_remove_assistance_twilio_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistance',
            name='tool1_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assistance',
            name='tool2_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='assistant_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='assistance',
            name='vapi_phone_number_id',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
