# Generated by Codex for Super Admin integrations.
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=160)),
                ("logo_url", models.TextField(blank=True, default="")),
                ("category", models.CharField(choices=[("Database", "Database"), ("Messaging", "Messaging"), ("Payments", "Payments"), ("Infrastructure", "Infrastructure"), ("AI", "AI"), ("Analytics", "Analytics"), ("Other", "Other")], default="Other", max_length=40)),
                ("monthly_cost", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("currency", models.CharField(choices=[("USD", "USD"), ("AED", "AED"), ("GBP", "GBP"), ("EUR", "EUR")], default="USD", max_length=8)),
                ("notes", models.TextField(blank=True, default="")),
                ("status", models.CharField(choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"db_table": "integrations", "ordering": ["-created_at"]},
        ),
    ]
