# Generated by Django 5.2.1 on 2026-06-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='api_health',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('unknown', 'Unknown'), ('error', 'Error')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='integration',
            name='connection_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('configured', 'Configured'), ('requires_configuration', 'Requires Configuration'), ('disabled', 'Disabled'), ('error', 'Error')], default='requires_configuration', max_length=40),
        ),
        migrations.AddField(
            model_name='integration',
            name='documentation_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integration',
            name='environment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='integration',
            name='provider_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
    ]
