# Generated by Django 5.2.1 on 2025-05-29 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_alter_device_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='is_booked',
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('guest_no', models.PositiveIntegerField()),
                ('cell_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('reservation_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('accept', 'Accepted'), ('hold', 'On Hold'), ('cancel', 'Cancelled')], default='hold', max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='device.device')),
            ],
        ),
    ]
