# Generated by Django 5.2.1 on 2025-05-30 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0005_reservation_created_at_reservation_updated_at'),
        ('restaurant', '0007_alter_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurant.restaurant'),
        ),
    ]
