# Generated by Django 5.2.1 on 2025-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_reservation_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('accept', 'Accepted'), ('hold', 'Hold'), ('cancel', 'Cancelled')], default='hold', max_length=10),
        ),
    ]
