# Generated by Django 5.2.1 on 2025-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_alter_reservation_email_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='table_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
