# Generated by Django 5.2.1 on 2025-11-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_device_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='region',
            field=models.CharField(blank=True, default='Primary', max_length=50),
        ),
    ]
