# Generated by Django 5.2.1 on 2025-12-01 18:03

import uuid
from django.db import migrations, models

def deduplicate_uuids(apps, schema_editor):
    Device = apps.get_model('device', 'Device')
    for device in Device.objects.all():
        device.uuid = uuid.uuid4()
        device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_device_uuid'),
    ]

    operations = [
        migrations.RunPython(deduplicate_uuids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
