# Generated by Django 5.2.1 on 2025-12-04 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_device_table_token_guestsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='table_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
