# Generated by Django 5.2.1 on 2025-12-04 15:54

import uuid
from django.db import migrations, models


def fix_duplicates(apps, schema_editor):
    Device = apps.get_model('device', 'Device')
    for device in Device.objects.all():
        device.table_token = uuid.uuid4()
        device.save()

class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_device_table_token_guestsession'),
    ]

    operations = [
        migrations.RunPython(fix_duplicates),
        migrations.AlterField(
            model_name='device',
            name='table_token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
