# Generated by Django 5.2.1 on 2025-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_alter_device_table_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/qr_codes/'),
        ),
    ]
