# Generated by Django 5.2.1 on 2026-06-06 20:41

from datetime import timedelta
from django.db import migrations, models


def backfill_reservation_snapshots(apps, schema_editor):
    Reservation = apps.get_model('device', 'Reservation')
    for reservation in Reservation.objects.select_related('device', 'restaurant').all():
        update_fields = []
        if reservation.device_id:
            if not reservation.restaurant_id:
                reservation.restaurant_id = reservation.device.restaurant_id
                update_fields.append('restaurant')
            if not reservation.table_name:
                reservation.table_name = reservation.device.table_name or ''
                update_fields.append('table_name')
        if reservation.reservation_time and not reservation.end_time:
            reservation.end_time = reservation.reservation_time + timedelta(
                minutes=int(reservation.duration_minutes or 90) + int(reservation.buffer_minutes or 10)
            )
            update_fields.append('end_time')
        if update_fields:
            reservation.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0015_dashboard_performance_indexes'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='actual_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='actual_seated_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='custom_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='reservation',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extension_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='missing_fields',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='raw_customer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='source',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('web', 'Web'), ('walk_in', 'Walk-in'), ('google', 'Google')], default='dashboard', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='table_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='reservation',
            name='updated_by_staff_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='whatsapp_chat_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('confirmed', 'Confirmed'), ('overdue', 'Overdue'), ('seated', 'Seated'), ('extended', 'Extended'), ('finished', 'Finished'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('accept', 'Accepted'), ('hold', 'Hold'), ('cancel', 'Cancelled')], default='hold', max_length=20),
        ),
        migrations.RunPython(backfill_reservation_snapshots, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['restaurant', 'source'], name='reservation_rest_source_idx'),
        ),
    ]
