# Generated by Django 5.2.1 on 2025-05-22 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Username may contain letters, digits, spaces and @/./+/-/_ characters.', regex='^[\\w\\s.@+-]+$')]),
        ),
    ]
