# Generated by Django 5.2.1 on 2025-05-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefstaff',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
