# Generated by Django 5.2.1 on 2025-05-24 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_chefstaff_updated_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verified',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
