# Generated by Django 5.2.1 on 2025-06-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefstaff',
            name='action',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold')], default='pending', max_length=10),
        ),
    ]
