# Generated by Django 5.2.1 on 2025-12-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_passwordresetotp_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('chef', 'Chef'), ('staff', 'Staff'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
