"""
Django settings for RESTAURANTS project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
import environ
# env = environ.Env()
# environ.Env.read_env()
env = environ.Env(
    DEBUG=(bool, False)
)

# Read .env file
environ.Env.read_env('.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-fallback-key-change-in-production-12345')

# SECURITY WARNING: don't run with debug turned on in production!

# Database configuration - supports both SQLite (local) and PostgreSQL (Docker)
USE_SQLITE = env.bool('USE_SQLITE', default=False)
# --- CRITICAL DEBUG MODE ---
DEBUG = True

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # HARDCODED EXTERNAL DATABASE CONNECTION
    # Bypassing all environment variables to ensure connectivity
    print("!!! USING HARDCODED EXTERNAL DATABASE CONFIG !!!")
    
    DATABASES = {
        'default': env.db_url_config(
             'postgresql://cleverdining_db_user:41ETCSVh25R43IG4vJrL0FHaFOcUoClV@dpg-d4ivnueuk2gs73bh11i0-a.oregon-postgres.render.com/cleverdining_db?sslmode=require'
        )
    }

    print(f"  ! Active Host: {DATABASES['default']['HOST']}")
