"""
Django settings for RESTAURANTS project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import os
import environ
from core.logging_config import get_logging_config
# env = environ.Env()
# environ.Env.read_env()
env = environ.Env(
    DEBUG=(bool, False)
)

# Read .env file
environ.Env.read_env('.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='cleverbiz-local-fallback-7f3c1a9b2d6e4f8091a3c5e7b9d2f4a6c8e0b1d3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

ALLOWED_HOSTS = ["*"]

# Add Render.com URL if available
RENDER_EXTERNAL_HOSTNAME = env('RENDER_EXTERNAL_HOSTNAME', default=None)
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

CSRF_TRUSTED_ORIGINS = [
    "https://abc.winaclaim.com",
    "https://clever-biz.netlify.app",
    "https://clever-biz2.netlify.app",
    "https://officialcleverdining.netlify.app",
    "https://cleverdining-2.onrender.com",
    "https://cleverdining-backend.onrender.com",
    "http://localhost:4173",
    "http://localhost:4174",
    "http://localhost:4175",
    "http://localhost:4176",
    "http://localhost:5175",
    "http://localhost:5176",
    "http://localhost:5177",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
    "http://127.0.0.1:4174",
    "http://127.0.0.1:4175",
    "http://127.0.0.1:4176",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5176",
    "http://127.0.0.1:5177",
    "https://officialcleverdiningcustomer.netlify.app",
]

# Add Render.com URL to CSRF trusted origins
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f"https://{RENDER_EXTERNAL_HOSTNAME}")

# Security Settings for Render (SSL Termination)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
_SECURE_DEPLOYMENT_DEFAULT = bool(RENDER_EXTERNAL_HOSTNAME and not DEBUG)
SECURE_SSL_REDIRECT = env.bool('SECURE_SSL_REDIRECT', default=_SECURE_DEPLOYMENT_DEFAULT)
SESSION_COOKIE_SECURE = env.bool('SESSION_COOKIE_SECURE', default=_SECURE_DEPLOYMENT_DEFAULT)
CSRF_COOKIE_SECURE = env.bool('CSRF_COOKIE_SECURE', default=_SECURE_DEPLOYMENT_DEFAULT)
SECURE_HSTS_SECONDS = env.int('SECURE_HSTS_SECONDS', default=31536000 if _SECURE_DEPLOYMENT_DEFAULT else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=_SECURE_DEPLOYMENT_DEFAULT)
SECURE_HSTS_PRELOAD = env.bool('SECURE_HSTS_PRELOAD', default=_SECURE_DEPLOYMENT_DEFAULT)

CORS_ALLOW_ALL_ORIGINS = False  # Use explicit allowlist below
CORS_ALLOWED_ORIGINS = [
    "https://abc.winaclaim.com",
    "https://clever-biz.netlify.app",
    "https://clever-biz2.netlify.app",
    "https://officialcleverdining.netlify.app",
    "https://officialcleverdiningcustomer.netlify.app",
    "http://localhost:4173",
    "http://localhost:4174",
    "http://localhost:4175",
    "http://localhost:4176",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:5175",
    "http://localhost:5176",
    "http://localhost:5177",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:4173",
    "http://127.0.0.1:4174",
    "http://127.0.0.1:4175",
    "http://127.0.0.1:4176",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:5175",
    "http://127.0.0.1:5176",
    "http://127.0.0.1:5177",
]

# Netlify preview/custom deploy URLs change over time. Keep the explicit
# allowlist above for known production domains, and allow same-project Netlify
# origins so deployed previews do not fail browser preflight requests.
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://[a-z0-9-]+\.netlify\.app$",
    r"^http://localhost:\d+$",
    r"^http://127\.0\.0\.1:\d+$",
]

# Allow credentials for authenticated requests
CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400

# Explicitly allow OPTIONS method for CORS preflight
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Allow common headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-guest-session-token',
]

# Allow base64 branding payloads (logo/cover images) up to 25MB.
DATA_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 25 * 1024 * 1024


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'accounts',
    'owners',
    'chef',
    'staff',
    'customer',
    'category',
    'item',
    'restaurant',
    'device',
    'order',
    'review',
    'message',
    'policy',
    'adminapi',
    'vapi',
    'subscription',
    'payment'
]

MIDDLEWARE = [
    'core.cors.PermanentCorsMiddleware',  # First: keep CORS headers on preflight and error responses
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.gzip.GZipMiddleware',  # Compress responses — 60-80% smaller JSON payloads
    'corsheaders.middleware.CorsMiddleware',  # CORS must be early, before CommonMiddleware
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.RequestContextLoggingMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'restaurant.middleware.JSONExceptionMiddleware',  # Catch all exceptions and return JSON
]

ROOT_URLCONF = 'RESTAURANTS.urls'
AUTH_USER_MODEL = 'accounts.User'



# access token time 
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Channels
ASGI_APPLICATION = 'RESTAURANTS.asgi.application'
WSGI_APPLICATION = 'RESTAURANTS.wsgi.application'


# Channel layers
REDIS_HOST = env('REDIS_HOST', default=None)
REDIS_URL = env('REDIS_URL', default=None)  # Standard Render/Heroku Var


def _redis_available(redis_url=None, redis_host=None):
    """
    Verify Redis connectivity at startup.
    If Redis is misconfigured/unreachable, fallback to in-memory channels
    so websocket handshakes do not fail with HTTP 500.
    """
    try:
        import redis

        if redis_url:
            client = redis.Redis.from_url(
                redis_url,
                socket_connect_timeout=1,
                socket_timeout=1,
                retry_on_timeout=False,
            )
        else:
            client = redis.Redis(
                host=redis_host,
                port=6379,
                socket_connect_timeout=1,
                socket_timeout=1,
                retry_on_timeout=False,
            )
        client.ping()
        return True
    except Exception as exc:
        import sys
        target = redis_url or f"{redis_host}:6379"
        print(f"[STARTUP] ⚠️ Redis unavailable at {target}: {exc}", file=sys.stderr)
        return False


if REDIS_URL and _redis_available(redis_url=REDIS_URL):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [REDIS_URL],
            },
        },
    }
    print(f"[STARTUP] ✅ CHANNEL_LAYERS = RedisChannelLayer (REDIS_URL={REDIS_URL[:30]}...)")
elif REDIS_HOST and REDIS_HOST != 'localhost' and _redis_available(redis_host=REDIS_HOST):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                "hosts": [(REDIS_HOST, 6379)],
            },
        },
    }
    print(f"[STARTUP] ✅ CHANNEL_LAYERS = RedisChannelLayer (REDIS_HOST={REDIS_HOST})")
else:
    # ⚠️ InMemory is single-process only, but prevents websocket hard failures
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        },
    }
    import sys
    print("[STARTUP] ⚠️⚠️⚠️ CHANNEL_LAYERS = InMemoryChannelLayer — REAL-TIME UPDATES MAY NOT WORK ACROSS PROCESSES!", file=sys.stderr)
    print("[STARTUP] ⚠️ Fix REDIS_URL/REDIS_HOST to restore multi-process real-time messaging.", file=sys.stderr)


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],  
    "DEFAULT_FILTER_BACKENDS": [
        "core.filter_backends.SchemaSafeDjangoFilterBackend"
    ],
    "DEFAULT_SCHEMA_CLASS": "core.schema.UniqueOperationIdAutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
    'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.IsAuthenticated',
],
    'EXCEPTION_HANDLER': 'restaurant.exceptions.custom_exception_handler',
}

LOGIN_REDIRECT_URL = "/profile/"


AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.EmailOrUsernameModelBackend',
    'django.contrib.auth.backends.ModelBackend',  # keep for admin and fallback
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# Media Files (Uploads)
GS_BUCKET_NAME = env('GS_BUCKET_NAME', default=None)

if GS_BUCKET_NAME:
    # Google Cloud Storage Configuration
    DEFAULT_FILE_STORAGE = "storages.backends.gcloud.GoogleCloudStorage"
    GS_PROJECT_ID = env('GS_PROJECT_ID', default=None) # Optional if in creds
    
    # Load Credentials from JSON string in Env Var
    import json
    from google.oauth2 import service_account
    GS_CREDENTIALS_JSON = env('GS_CREDENTIALS', default='{}')
    try:
        GS_CREDENTIALS = service_account.Credentials.from_service_account_info(
            json.loads(GS_CREDENTIALS_JSON)
        )
    except Exception as e:
        print(f"Warning: Failed to load GS_CREDENTIALS: {e}")
        GS_CREDENTIALS = None

    MEDIA_URL = f"https://storage.googleapis.com/{GS_BUCKET_NAME}/"
else:
    # Local Storage (or Render Disk)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = env('MEDIA_ROOT', default=os.path.join(BASE_DIR, 'media'))

STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for serving static files in production
# Use basic storage for ASGI compatibility
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Ensure WhiteNoise serves files correctly
WHITENOISE_ROOT = os.path.join(BASE_DIR, 'staticfiles')
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Email Configuration — auto-switches between SMTP (production) and Console (dev)
_email_user = env("EMAIL", default='')
if _email_user:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_USE_TLS = True
    EMAIL_PORT = 587
    EMAIL_HOST_USER = _email_user
    EMAIL_HOST_PASSWORD = env("EMAIL_PASSWORD", default='')
    DEFAULT_FROM_EMAIL = f'CleverDining <{_email_user}>'
else:
    # Fallback: print emails to terminal (development)
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'noreply@cleverdining.com'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Logging configuration
LOGGING = get_logging_config(env('LOG_LEVEL', default='INFO'))

STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='')


#env

VAPI_API=env('VAPI_API', default='')
STRIPE_SECRET_KEY=env('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET=env('STRIPE_WEBHOOK_SECRET', default='')

# OpenAI Configuration
OPENAI_API_KEY = env('OPENAI_API_KEY', default=None)
# Database configuration - supports both SQLite (local) and PostgreSQL (Docker)
USE_SQLITE = env.bool('USE_SQLITE', default=False)

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    # HARDCODED EXTERNAL DATABASE CONNECTION (Public URL)
    # Using 'prefer' to attempt SSL but allow fallback/negotiation
    print("!!! USING HARDCODED EXTERNAL DATABASE CONFIG (SSL PREFER) !!!")
    
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'cleverdining_db',
            'USER': 'cleverdining_db_user',
            'PASSWORD': env('DATABASE_PASSWORD', default='41ETCSVh25R43IG4vJrL0FHaFOcUoClV'),
            'HOST': 'dpg-d4ivnueuk2gs73bh11i0-a.oregon-postgres.render.com',
            'PORT': '5432',
            # Render's small Postgres plans have very limited connection slots.
            # Closing request connections by default prevents the app from
            # holding idle connections until the database refuses new work.
            'CONN_MAX_AGE': env.int('DB_CONN_MAX_AGE', default=0),
            'CONN_HEALTH_CHECKS': env.bool('DB_CONN_HEALTH_CHECKS', default=True),
            'OPTIONS': {
                'sslmode': 'prefer',
                'connect_timeout': 10,
            },
        }
    }

    print(f"  ! Active Host: {DATABASES['default']['HOST']}")


# Sentry configuration (non-invasive: disabled unless SENTRY_DSN is set)
SENTRY_DSN = env('SENTRY_DSN', default='')
if SENTRY_DSN:
    try:
        import sentry_sdk
        from sentry_sdk.integrations.django import DjangoIntegration
        from sentry_sdk.integrations.redis import RedisIntegration
        from core.sentry_config import before_send as sentry_before_send

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[
                DjangoIntegration(),
                RedisIntegration(),
            ],
            traces_sample_rate=env.float('SENTRY_TRACES_SAMPLE_RATE', default=0.1),
            profiles_sample_rate=env.float('SENTRY_PROFILES_SAMPLE_RATE', default=0.0),
            send_default_pii=True,
            environment=env('SENTRY_ENVIRONMENT', default='production' if not DEBUG else 'development'),
            release=env('SENTRY_RELEASE', default=''),
            before_send=sentry_before_send,
        )
    except Exception as sentry_init_error:
        import sys

        print(f"[STARTUP] ⚠️ Failed to initialize Sentry: {sentry_init_error}", file=sys.stderr)
