# Generated by Django 5.2.1 on 2025-05-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='new_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
