# Generated by Django 5.2.1 on 2025-12-25 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_unreadcount_chatmessage_is_read_chatmessage_read_at'),
        ('restaurant', '0011_businessday_closed_by_businessday_total_card_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='business_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='restaurant.businessday'),
        ),
    ]
