# Generated by Django 5.2.1 on 2025-12-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_device_qr_code_image'),
        ('message', '0005_chatmessage_business_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='device.guestsession'),
        ),
    ]
