# Generated by Django 5.2.1 on 2026-05-05 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_device_qr_code_image'),
        ('message', '0006_chatmessage_guest_session'),
        ('restaurant', '0019_brandconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='new_message',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['restaurant', 'is_read', 'is_from_device'], name='message_cha_restaur_bd089f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['device', 'timestamp'], name='message_cha_device__75e764_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['guest_session', 'timestamp'], name='message_cha_guest_s_01a2af_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender', 'is_read'], name='message_cha_sender__8f260f_idx'),
        ),
    ]
