# Generated by Django 5.2.1 on 2026-05-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_device_qr_code_image'),
        ('message', '0007_alter_chatmessage_options_alter_chatmessage_is_read_and_more'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(blank=True, db_index=True, null=True)),
                ('table_name', models.CharField(blank=True, default='', max_length=80)),
                ('type', models.CharField(choices=[('chat', 'Chat'), ('assistance', 'Assistance'), ('call_waiter', 'Call Waiter')], default='chat', max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged'), ('read', 'Read')], db_index=True, default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_messages', to='device.device')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_messages', to='restaurant.restaurant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['restaurant', 'status', 'created_at'], name='message_tab_restaur_6440e3_idx'), models.Index(fields=['table_number', 'created_at'], name='message_tab_table_n_b86328_idx')],
            },
        ),
    ]
