# Generated by Django 5.2.1 on 2026-07-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0008_tablemessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablemessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("acknowledged", "Acknowledged"),
                    ("read", "Read"),
                    ("resolved", "Resolved"),
                ],
                db_index=True,
                default="pending",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="tablemessage",
            name="type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("assistance", "Assistance"),
                    ("call_waiter", "Call Waiter"),
                    ("cash_payment", "Cash Payment"),
                ],
                default="chat",
                max_length=30,
            ),
        ),
    ]
