# Generated by Django 5.2.1 on 2025-11-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/category_icons/'),
        ),
    ]
