# Generated by Django 5.2.1 on 2026-04-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('main', 'Main'), ('drink', 'Drink'), ('dessert', 'Dessert'), ('starter', 'Starter'), ('other', 'Other')], db_index=True, default='other', max_length=20),
        ),
    ]
