# Generated by Django 5.2.1 on 2025-12-04 15:56

import django.db.models.deletion
from django.db import migrations, models


def add_guest_session_field(apps, schema_editor):
    from django.db import connection
    # Use introspection to be database agnostic (SQLite friendly)
    with connection.cursor() as cursor:
        try:
            # Check if table exists first
            tables = connection.introspection.table_names(cursor)
            if 'order_order' not in tables:
                return # Table doesn't exist yet, so field definitely doesn't
            
            # Check columns
            description = connection.introspection.get_table_description(cursor, 'order_order')
            columns = [col.name for col in description]
            if 'guest_session_id' in columns:
                return
        except Exception:
            # Fallback or ignore if something weird happens, let migration try to add field
            pass

    Order = apps.get_model('order', 'Order')
    GuestSession = apps.get_model('device', 'GuestSession')
    field = models.ForeignKey(
        GuestSession,
        blank=True, 
        null=True, 
        on_delete=django.db.models.deletion.SET_NULL, 
        related_name='orders'
    )
    field.set_attributes_from_name('guest_session')
    schema_editor.add_field(Order, field)

class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_alter_device_table_token'),
        ('item', '0007_item_sub_category'),
        ('order', '0002_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(add_guest_session_field),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='order',
                    name='guest_session',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='device.guestsession'),
                ),
            ]
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='device.device')),
                ('guest_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='device.guestsession')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cart')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item')),
            ],
        ),
    ]
