# Generated by Django 5.2.1 on 2025-12-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_tip_amount_order_tip_percentage_order_tip_type_and_more'),
        ('restaurant', '0010_businessday'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='business_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurant.businessday'),
        ),
    ]
