# Generated by Django 5.2.1 on 2026-04-09 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_device_qr_code_image'),
        ('item', '0009_item_tags'),
        ('order', '0006_order_business_day'),
        ('restaurant', '0018_restaurant_region_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsellEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=120)),
                ('table_number', models.CharField(blank=True, default='', max_length=50)),
                ('trigger_point', models.CharField(choices=[('add_to_cart', 'Add To Cart'), ('cart', 'Cart'), ('before_payment', 'Before Payment')], db_index=True, max_length=30)),
                ('action', models.CharField(choices=[('shown', 'Shown'), ('accepted', 'Accepted'), ('dismissed', 'Dismissed'), ('declined', 'Declined')], db_index=True, max_length=20)),
                ('upsell_item_name', models.CharField(blank=True, default='', max_length=255)),
                ('upsell_category', models.CharField(blank=True, default='', max_length=120)),
                ('upsell_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cart_value_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cart_item_count', models.PositiveIntegerField(default=0)),
                ('hour_of_day', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('day_of_week', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UpsellRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pair', 'Pair'), ('block', 'Block')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpsellSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('strategy', models.CharField(choices=[('balanced', 'Balanced'), ('margin', 'Margin'), ('volume', 'Volume')], default='balanced', max_length=20)),
                ('aggressiveness', models.CharField(choices=[('subtle', 'Subtle'), ('moderate', 'Moderate'), ('aggressive', 'Aggressive')], default='moderate', max_length=20)),
                ('show_after_add_to_cart', models.BooleanField(default=True)),
                ('show_in_cart', models.BooleanField(default=True)),
                ('show_before_payment', models.BooleanField(default=True)),
                ('tone', models.CharField(choices=[('friendly', 'Friendly'), ('professional', 'Professional'), ('playful', 'Playful')], default='friendly', max_length=20)),
                ('prioritized_categories', models.TextField(blank=True, default='')),
                ('category_role_map', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='upsellevent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_events', to='device.device'),
        ),
        migrations.AddField(
            model_name='upsellevent',
            name='guest_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_events', to='device.guestsession'),
        ),
        migrations.AddField(
            model_name='upsellevent',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_events', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='upsellevent',
            name='upsell_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upsell_events', to='item.item'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_rules', to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='source_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_source_rules', to='item.item'),
        ),
        migrations.AddField(
            model_name='upsellrule',
            name='target_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_target_rules', to='item.item'),
        ),
        migrations.AddField(
            model_name='upsellsetting',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_setting', to='restaurant.restaurant'),
        ),
        migrations.AddIndex(
            model_name='upsellevent',
            index=models.Index(fields=['restaurant', 'created_at'], name='order_upsel_restaur_b84fa3_idx'),
        ),
        migrations.AddIndex(
            model_name='upsellevent',
            index=models.Index(fields=['restaurant', 'trigger_point', 'action'], name='order_upsel_restaur_851271_idx'),
        ),
        migrations.AddIndex(
            model_name='upsellevent',
            index=models.Index(fields=['restaurant', 'table_number', 'created_at'], name='order_upsel_restaur_c8a688_idx'),
        ),
        migrations.AddIndex(
            model_name='upsellrule',
            index=models.Index(fields=['restaurant', 'type', 'is_active'], name='order_upsel_restaur_c3a6f0_idx'),
        ),
        migrations.AddIndex(
            model_name='upsellrule',
            index=models.Index(fields=['source_item', 'target_item'], name='order_upsel_source__9ea84d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='upsellrule',
            unique_together={('restaurant', 'type', 'source_item', 'target_item')},
        ),
        migrations.AddIndex(
            model_name='upsellsetting',
            index=models.Index(fields=['restaurant'], name='order_upsel_restaur_8b368a_idx'),
        ),
        migrations.AddIndex(
            model_name='upsellsetting',
            index=models.Index(fields=['enabled'], name='order_upsel_enabled_e09c2f_idx'),
        ),
    ]
