# Generated by Django 5.2.1 on 2026-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_device_qr_code_image'),
        ('order', '0007_upsellevent_upsellrule_upsellsetting_and_more'),
        ('restaurant', '0018_restaurant_region_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('preparing', 'Preparing'), ('served', 'Served'), ('delivered', 'Delivered'), ('paid', 'Paid'), ('awaiting_cash', 'Awaiting Cash'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'created_time'], name='order_order_restaur_92b32a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['restaurant', 'status'], name='order_order_restaur_cd860d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['guest_session'], name='order_order_guest_s_f7478c_idx'),
        ),
    ]
