# Generated by Django 5.2.1 on 2026-04-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('pending_cash', 'Pending Cash'), ('paid', 'Paid')], default='unpaid', max_length=50, null=True),
        ),
    ]
