# Generated by Django 5.2.1 on 2026-04-24 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_item_item_item_restaur_26d236_idx'),
        ('order', '0010_order_notes'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsellrule',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upsell_source_rules', to='item.item'),
        ),
        migrations.AlterField(
            model_name='upsellrule',
            name='type',
            field=models.CharField(choices=[('pair', 'Pair'), ('block', 'Block'), ('global_block', 'Global Block')], max_length=20),
        ),
        migrations.AlterField(
            model_name='upsellsetting',
            name='strategy',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('highest_margin', 'Highest Margin'), ('highest_conversion', 'Highest Conversion'), ('premium_experience', 'Premium Experience'), ('inventory_movement', 'Inventory Movement'), ('margin', 'Margin (Legacy)'), ('volume', 'Volume (Legacy)')], default='balanced', max_length=20),
        ),
        migrations.AlterField(
            model_name='upsellsetting',
            name='tone',
            field=models.CharField(choices=[('friendly', 'Friendly'), ('premium', 'Premium'), ('minimal', 'Minimal'), ('luxury_casual', 'Luxury Casual'), ('professional', 'Professional (Legacy)'), ('playful', 'Playful (Legacy)')], default='friendly', max_length=20),
        ),
        migrations.CreateModel(
            name='UpsellItemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('inventory_priority', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_item_settings', to='item.item')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_item_settings', to='restaurant.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'enabled'], name='order_upsel_restaur_8a6972_idx'), models.Index(fields=['restaurant', 'inventory_priority'], name='order_upsel_restaur_626405_idx')],
                'unique_together': {('restaurant', 'item')},
            },
        ),
    ]
