# Generated by Django 5.2.1 on 2026-04-24 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_item_item_item_restaur_26d236_idx'),
        ('order', '0011_alter_upsellrule_source_item_alter_upsellrule_type_and_more'),
        ('restaurant', '0019_brandconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_order_frequency', models.PositiveIntegerField(default=0)),
                ('association_strength', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('times_shown', models.PositiveIntegerField(default=0)),
                ('times_accepted', models.PositiveIntegerField(default=0)),
                ('times_dismissed', models.PositiveIntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('last_computed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_associations', to='restaurant.restaurant')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_association_sources', to='item.item')),
                ('target_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_association_targets', to='item.item')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'source_item'], name='order_itema_restaur_14a355_idx'), models.Index(fields=['restaurant', 'target_item'], name='order_itema_restaur_b371cf_idx'), models.Index(fields=['restaurant', 'co_order_frequency'], name='order_itema_restaur_7b8cca_idx'), models.Index(fields=['restaurant', 'association_strength'], name='order_itema_restaur_48363a_idx')],
                'unique_together': {('restaurant', 'source_item', 'target_item')},
            },
        ),
    ]
