# Generated by Django 5.2.1 on 2026-07-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsellsetting',
            name='strategy',
            field=models.CharField(choices=[('balanced', 'Balanced'), ('max_revenue', 'Maximise Revenue'), ('move_stock', 'Move Stock'), ('highest_margin', 'Highest Margin'), ('highest_conversion', 'Highest Conversion'), ('premium_experience', 'Premium Experience'), ('inventory_movement', 'Inventory Movement'), ('margin', 'Margin (Legacy)'), ('volume', 'Volume (Legacy)')], default='balanced', max_length=20),
        ),
    ]
