# Generated by Django 5.2.1 on 2026-07-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_seed_pranay_menu_by_account_identity'),
        ('order', '0015_alter_order_status'),
        ('restaurant', '0022_brandconfig_pay_before_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsellLLMDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_key', models.CharField(max_length=64, unique=True)),
                ('settings_signature', models.CharField(db_index=True, max_length=64)),
                ('candidate_ids', models.JSONField(blank=True, default=list)),
                ('decision', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upsell_llm_decisions', to='restaurant.restaurant')),
                ('selected_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upsell_llm_selected_decisions', to='item.item')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upsell_llm_source_decisions', to='item.item')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant', 'source_item', 'expires_at'], name='order_upsel_restaur_2066e5_idx'), models.Index(fields=['restaurant', 'settings_signature', 'expires_at'], name='order_upsel_restaur_e41681_idx')],
            },
        ),
    ]
