# Generated by Django 5.2.1 on 2025-05-26 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
