# Generated by Django 5.2.1 on 2025-11-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_remove_restaurant_starting_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='media/restaurant_logos/'),
        ),
    ]
