# Generated by Django 5.2.1 on 2025-12-25 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_businessday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessday',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_business_days', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessday',
            name='total_card_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='businessday',
            name='total_cash_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='businessday',
            name='total_tips',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
