# Generated by Django 5.1.3 on 2026-01-27
# Manually created migration for google_review_url field

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_businessday_closed_by_businessday_total_card_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_review_url',
            field=models.URLField(blank=True, help_text='Google Business Profile review URL', max_length=500, null=True),
        ),
    ]
