# Generated by Django 5.2.1 on 2026-02-03 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_restaurant_google_review_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='google_review_url',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='plan',
            field=models.CharField(choices=[('standard', 'Standard'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='subscription_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_api_version',
            field=models.CharField(default='v20.0', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_app_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_app_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_business_display_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_phone_number_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_waba_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_webhook_callback_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='whatsapp_webhook_verify_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
