# Generated by Django 5.2.1 on 2026-02-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_remove_restaurant_google_review_url_restaurant_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='qr_codes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='table_count',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
