# Generated by Django 5.2.3 on 2026-04-07

from django.db import migrations, models


def backfill_region_fields(apps, schema_editor):
    Restaurant = apps.get_model('restaurant', 'Restaurant')

    def infer_region(country, currency):
        country_text = (country or '').strip().lower()
        currency_text = (currency or '').strip().upper()

        if currency_text == 'GBP':
            return 'UK'

        uk_markers = (
            'uk',
            'united kingdom',
            'great britain',
            'england',
            'london',
            'gb',
        )
        if any(marker in country_text for marker in uk_markers):
            return 'UK'

        return 'UAE'

    for restaurant in Restaurant.objects.all().iterator():
        region = infer_region(getattr(restaurant, 'country', ''), getattr(restaurant, 'currency', ''))
        if region == 'UK':
            defaults = {
                'currency': 'GBP',
                'timezone': 'Europe/London',
                'country_code': '+44',
                'default_payment_provider': 'stripe',
            }
        else:
            defaults = {
                'currency': 'AED',
                'timezone': 'Asia/Dubai',
                'country_code': '+971',
                'default_payment_provider': 'stripe',
            }

        payment_processor = (getattr(restaurant, 'payment_processor', '') or '').strip().lower()
        if payment_processor:
            defaults['default_payment_provider'] = payment_processor

        Restaurant.objects.filter(pk=restaurant.pk).update(
            region=region,
            currency=defaults['currency'],
            timezone=defaults['timezone'],
            country_code=defaults['country_code'],
            default_payment_provider=defaults['default_payment_provider'],
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0017_restaurant_city_country_payment_processor'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='country_code',
            field=models.CharField(default='+971', max_length=8),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='default_payment_provider',
            field=models.CharField(default='stripe', max_length=30),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(
                choices=[('UAE', 'UAE'), ('UK', 'UK')],
                db_index=True,
                default='UAE',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(default='Asia/Dubai', max_length=64),
        ),
        migrations.RunPython(backfill_region_fields, noop_reverse),
    ]
