# Generated by Django 5.2.3 on 2026-04-14

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0018_restaurant_region_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_name', models.TextField(default='My Restaurant')),
                ('logo_url', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('primary_color', models.CharField(default='#0055FE', max_length=7)),
                ('secondary_color', models.CharField(blank=True, max_length=7, null=True)),
                ('accent_color', models.CharField(blank=True, max_length=7, null=True)),
                ('theme_preset', models.TextField(default='classic_clean')),
                ('font_preset', models.TextField(default='modern')),
                ('tagline', models.TextField(blank=True, null=True)),
                ('branding_enabled', models.BooleanField(default=False)),
                ('instagram_url', models.TextField(blank=True, null=True)),
                ('facebook_url', models.TextField(blank=True, null=True)),
                ('tiktok_url', models.TextField(blank=True, null=True)),
                ('twitter_url', models.TextField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True)),
                ('wifi_name', models.TextField(blank=True, null=True)),
                ('wifi_password', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_config', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'brand_configs',
            },
        ),
    ]
