# Generated by Django 5.2.1 on 2025-12-10 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        # migrations.AlterField(
        #     model_name='staff',
        #     name='role',
        #     field=models.CharField(choices=[('manager', 'Manager'), ('staff', 'Staff'), ('chef', 'Chef'), ('waiter', 'Waiter')], default='waiter', max_length=50),
        # ),
        # migrations.AlterField(
        #     model_name='staff',
        #     name='user',
        #     field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        # ),
    ]
