# Generated by Django 5.2.1 on 2025-12-04 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentgateway_payment_cancel_reason_and_more'),
        ('restaurant', '0009_restaurant_logo'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_payments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='confirmed_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_payments', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider',
            field=models.CharField(default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='raw_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_gateways', to='restaurant.restaurant'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentgateway',
            unique_together={('restaurant', 'provider')},
        ),
    ]
