# Generated by Django 5.2.1 on 2025-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_cancelled_by_payment_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('checkout', 'Checkout.com'), ('paytabs', 'PayTabs')], max_length=20),
        ),
    ]
