# Generated by Django 5.1.3 on 2026-01-27
# Manually created migration for wallet payment fields

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_paymentgateway_provider'),
    ]

    operations = [
        # Add wallet_token_reference to Payment model
        migrations.AddField(
            model_name='payment',
            name='wallet_token_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Update Payment provider choices to include wallet options
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(
                choices=[
                    ('stripe', 'Stripe'),
                    ('checkout', 'Checkout.com'),
                    ('paytabs', 'PayTabs'),
                    ('cash', 'Cash'),
                    ('apple_pay', 'Apple Pay'),
                    ('google_pay', 'Google Pay'),
                ],
                default='stripe',
                max_length=20,
            ),
        ),
        # Apple Pay fields on PaymentGateway
        migrations.AddField(
            model_name='paymentgateway',
            name='apple_pay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='apple_merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='apple_domain_verified',
            field=models.BooleanField(default=False),
        ),
        # Google Pay fields on PaymentGateway
        migrations.AddField(
            model_name='paymentgateway',
            name='google_pay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='google_merchant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='google_environment',
            field=models.CharField(
                choices=[('TEST', 'Test'), ('PRODUCTION', 'Production')],
                default='TEST',
                max_length=10,
            ),
        ),
    ]
