# Generated by Django 5.2.1 on 2026-04-14 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_payment_status'),
        ('payment', '0006_alter_provider_choices_payme'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_id_or_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='split_type',
            field=models.CharField(choices=[('full_bill', 'Full Bill'), ('evenly', 'Evenly'), ('my_items', 'My Items')], default='full_bill', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_or_order_id', models.CharField(blank=True, default='', max_length=120)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('split_method', models.CharField(blank=True, choices=[('', 'Unset'), ('full_bill', 'Full Bill'), ('evenly', 'Evenly'), ('my_items', 'My Items')], default='', max_length=20)),
                ('split_count', models.PositiveIntegerField(blank=True, null=True)),
                ('per_person_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_shares_count', models.PositiveIntegerField(default=0)),
                ('unpaid_shares_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='order.order')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.orderbill'),
        ),
        migrations.CreateModel(
            name='OrderBillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unpaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_items', to='payment.orderbill')),
                ('order_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_item', to='order.orderitem')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(blank=True, default='', max_length=255)),
                ('allocated_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('allocation_type', models.CharField(choices=[('bill', 'Bill'), ('share', 'Share'), ('item', 'Item'), ('fee', 'Fee')], default='bill', max_length=20)),
                ('participant_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payment.orderbill')),
                ('bill_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='payment.orderbillitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='payment.payment')),
            ],
        ),
        migrations.AddIndex(
            model_name='orderbill',
            index=models.Index(fields=['payment_status'], name='payment_ord_payment_8b323b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbill',
            index=models.Index(fields=['split_method'], name='payment_ord_split_m_ce7cee_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbill',
            index=models.Index(fields=['updated_at'], name='payment_ord_updated_bab4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbillitem',
            index=models.Index(fields=['bill', 'item_status'], name='payment_ord_bill_id_03c23c_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbillitem',
            index=models.Index(fields=['order_item'], name='payment_ord_order_i_b2219c_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['bill', 'allocation_type'], name='payment_pay_bill_id_c810e5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['participant_status'], name='payment_pay_partici_7e3892_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentallocation',
            index=models.Index(fields=['participant_id'], name='payment_pay_partici_63912d_idx'),
        ),
    ]
