# Generated by Django 5.2.1 on 2026-06-26 05:40

from django.db import migrations, models


def mark_existing_gateways_connected(apps, schema_editor):
    PaymentGateway = apps.get_model('payment', 'PaymentGateway')
    PaymentGateway.objects.filter(key_id__gt='', key_secret__gt='').update(connection_status='connected')


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_payment_payer_id_or_name_payment_split_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='connection_status',
            field=models.CharField(choices=[('not_configured', 'Not Configured'), ('connected', 'Connected'), ('error', 'Error'), ('disabled', 'Disabled')], default='not_configured', max_length=30),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='credentials_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='last_health_check_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='last_validation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='provider_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='sandbox_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentgateway',
            name='webhook_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('failing', 'Failing')], default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('checkout', 'Checkout.com'), ('paytabs', 'PayTabs'), ('payme', 'Payme'), ('adyen', 'Adyen'), ('worldpay', 'Worldpay'), ('sumup', 'SumUp'), ('square', 'Square'), ('cash', 'Cash'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')], default='stripe', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='key_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='key_secret',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('checkout', 'Checkout.com'), ('paytabs', 'PayTabs'), ('payme', 'PayMe'), ('adyen', 'Adyen'), ('worldpay', 'Worldpay'), ('sumup', 'SumUp'), ('square', 'Square')], max_length=20),
        ),
        migrations.RunPython(mark_existing_gateways_connected, noop_reverse),
    ]
