# Generated by Django 5.2.1 on 2026-06-27 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_paymentgateway_connection_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('payload_hash', models.CharField(max_length=64)),
                ('signature_hash', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='received', max_length=20)),
                ('replay_detected', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_events', to='payment.paymentgateway')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'provider_event_id'], name='payment_pay_provide_616410_idx'), models.Index(fields=['gateway', 'created_at'], name='payment_pay_gateway_80d649_idx'), models.Index(fields=['status', 'created_at'], name='payment_pay_status_bca83b_idx')],
                'unique_together': {('provider', 'gateway', 'provider_event_id')},
            },
        ),
    ]
